apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-mvc
  template:
    metadata:
      labels:
        app: aspnet-mvc
    spec:
      containers:
      - name: aspnet-mvc
        image: hdhopson/stockjock_monolith
        ports:
          - containerPort: 80
            name: aspnet-mvc-http   