jobs:
    # build_monolith:
    #   defaults:
    #     run:
    #       working-directory: StockJock_Monolith/
    #   runs-on: ubuntu-20.04
    #   steps:
    #     - uses: actions/checkout@v2.3.1
    #     - run: dotnet build
    
    # test_monolith:
    #   defaults:
    #     run:
    #       working-directory: StockJock_Monolith/
    #   runs-on: ubuntu-20.04
    #   steps:
    #     - uses: actions/checkout@v2.3.1
    #     - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
  
    # analyze_monolith:
    #   defaults:
    #     run:
    #       working-directory: StockJock_Monolith/
    #   needs: [build_monolith, test_monolith]
    #   runs-on: ubuntu-20.04
    #   steps:
    #     - uses: actions/checkout@v2.3.1
    #     - run: git fetch --unshallow
    #     - run: dotnet tool install --global dotnet-sonarscanner
    #     - run: | 
    #         dotnet sonarscanner begin -o:'droptophop' -k:'droptophop_RevyDevyP2' -d:sonar.login="d1eeb6dbaaba45e39a73bfe797967c066d30fa8a" -d:sonar.host.url='https://sonarcloud.io/'
    #         dotnet build
    #         dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger trx
    #         dotnet sonarscanner end -d:sonar.login='d1eeb6dbaaba45e39a73bfe797967c066d30fa8a'
    #       env: 
    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # package_monolith:
    #   defaults:
    #     run:
    #       working-directory: StockJock_Monolith/
    #   env:
    #     DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
    #     DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    #   needs: [analyze_monolith]
    #   runs-on: ubuntu-20.04
    #   steps:
    #     - uses: actions/checkout@v2.3.1
    #     - run: docker login --username ${DOCKER_LOGIN} --password ${DOCKER_TOKEN}
    #     - run: docker image build -t stockjock_monolith .
    #     - run: docker image tag stockjock_monolith hdhopson/stockjock_monolith
    #     - run: docker image push hdhopson/stockjock_monolith
    #     - run: docker logout

        # End Monolith 
    
    build_api:
      defaults:
        run:
          working-directory: ApiService/StockJockAPI/
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2.3.1
        - run: dotnet build
    
    test_api:
      defaults:
        run:
          working-directory: ApiService/StockJockAPI/
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2.3.1
        - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
  
    analyze_api:
      defaults:
        run:
          working-directory: ApiService/StockJockAPI/
      needs: [build_api, test_api]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2.3.1
        - run: git fetch --unshallow
        - run: dotnet tool install --global dotnet-sonarscanner
        - run: | 
            dotnet sonarscanner begin -o:'droptophop' -k:'droptophop_RevyDevyP2' -d:sonar.login="d1eeb6dbaaba45e39a73bfe797967c066d30fa8a" -d:sonar.host.url='https://sonarcloud.io/'
            dotnet build
            dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger trx
            dotnet sonarscanner end -d:sonar.login='d1eeb6dbaaba45e39a73bfe797967c066d30fa8a'
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    package_api:
      defaults:
        run:
          working-directory: ApiService/StockJockAPI/
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      needs: [analyze_api]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2.3.1
        - run: docker login --username ${DOCKER_LOGIN} --password ${DOCKER_TOKEN}
        - run: docker image build -t stockjock_api .
        - run: docker image tag stockjock_api hdhopson/stockjock_api
        - run: docker image push hdhopson/stockjock_api
        - run: docker logout

    deploy_api:
      defaults:
        run:
          working-directory: ApiService/StockJockAPI/
      env:
        AZURE_LOGIN: ${{ secrets.AZURE_LOGIN }}
        AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      needs: [package_api]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - run: az login --service-principal --username ${AZURE_LOGIN} --password ${AZURE_TOKEN} --tenant ${AZURE_TENANT}
        - run: az aks get-credentials --name haroldfridayaks --resource-group fridayaks --admin
        - run: kubectl apply --filename ./kubernetes/ApiService
        - run: kubectl rollout --restart --filename ./kubernetes/ApiService/k8s_deployment.yaml
        - run: az logout    

        # End API Service 

    # build_angular:
    #   defaults:
    #     run:
    #       working-directory: Angular/StockJockyNgClient/
    #   runs-on: ubuntu-20.04
    #   steps:
    #     - uses: actions/checkout@v2
    #     - run: npm ci
    #     - run: npm run build
    #     - run: npm run lint
  
name: cibuild
  
on: push
